[build]
builder = "nixpacks"
<<<<<<< HEAD
builderCommand = "pnpm install && pnpm build"
=======
buildCommand = "pnpm install --frozen-lockfile && pnpm build"
>>>>>>> 7fd43ae83b63db3cb28e177a5f07135d563dea81

[deploy]
startCommand = "node dist/index.js"
restartPolicyType = "on_failure"
<<<<<<< HEAD
restartPolicyMaxRetries = 3
healthcheckPath = "/health"
healthcheckTimeout = 60
=======
restartPolicyMaxRetries = 10
# healthcheckPath = "/health"
# healthcheckTimeout = 100

[nixpacks]
providers = ["node"]

>>>>>>> 7fd43ae83b63db3cb28e177a5f07135d563dea81
