[build]
buildCommand = "pnpm install --frozen-lockfile && pnpm build"

[deploy]
startCommand = "npx tsx src/server/index.ts"
healthcheckPath = "/health"
healthcheckTimeout = 60

[nixpacks]
providers = ["node"]
