[build]
builder = "NIXPACKS"
buildCommand = "pnpm install --frozen-lockfile && pnpm build"

[deploy]
startCommand = "node dist/server/index.cjs"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[nixpacks]
providers = ["node"]

[variables]
NIXPACKS_NODE_VERSION = "20.19.5"
NODE_VERSION = "20.19.5"
