[build]
builder = "nixpacks"
builderCommand = "pnpm install && pnpm build"

[deploy]
startCommand = "node dist/index.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
healthcheckPath = "/health"
healthcheckTimeout = 60
