[build]
buildCommand = "pnpm install --frozen-lockfile && pnpm build"

[deploy]
startCommand = "node dist/server/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 60

[nixpacks]
providers = ["node"]
