name: ci-build-and-railway
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.4.1
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: railwayapp/action-deploy@v1
        with:
          serviceId: ${{ secrets.RAILWAY_SERVICE_ID }}
          apiToken: ${{ secrets.RAILWAY_TOKEN }}
